### ISSUE TITLE
Waiting for the code

### ISSUE THREAD

**Issue by Hezip** [leggedrobotics/GMFCL#1]
Hi, I really like the framework that you proposed. 
And I am still waiting for the open-source code to do some researches.
Hope your can release it asap. 
Appreciate your work again!

**Comment by nubertj** [comment]
Dear @Hezip,
Thanks a lot for your message, and sorry that the open-sourcing did not happen so far.
After the paper there were pretty big changes in the framework, and I want to make sure that also the community can benefit from a more flexible and reliable framework.
I do what I can to upload the framework and a first use-case this week.

**Comment by Hezip** [comment]
Oh! Thank you very much for your prompt reply.
Looking for the great work!
