### ISSUE TITLE
suitable for indoor scene?

### ISSUE THREAD

**Issue by narutojxl** [leggedrobotics/GMFCL#8]
Hello author,
Thanks for sharing the work!  I roughly read the paper, if we deploy this dual graph into indoor scene for localization, is it suitable? I think the fallback graph of the paper is consider for gnss drop. In indoor environment, there is no gps, main graph always is active.

**Comment by nubertj** [comment]
hi @narutojxl,
Yeah exactly, this specific dual graph formulation is not necessarily too useful if you do not have a global reference frame that you would like to follow at all times.
However, you can simply disable the useFallbackGraph in the config, and it should work for general sensor fusion.

I am currently writing a paper about a more general approach, and will push the latest code after the paper is on arXiv.
This latest version will work indoors, outdoors, with relative and global factors without the current dual graph setup, hence simplify things.

I estimate that I will be able to push the code in the next 4-6 weeks.

**Comment by narutojxl** [comment]
Hi doctor @nubertj,  I am very excited and looking forward to trying your excellent work!
Best regards
narutojxl
