### ISSUE TITLE
Regarding fusing a stereo inertial sensor for performing Visual SLAM

### ISSUE THREAD

**Issue by Aishkrish18** [leggedrobotics/GMFCL#9]
Hello @nubertj ! Thank you for this excellent work. I was a part of the ETH Robotics Summer school and I learnt a lot on using this code to map and localise. 
I am currently working on my thesis on a similar topic at the moment and I wanted to ask if this Graph Msf can be used or modified to fuse stereo inertial cameras as well? Is it mandatory to have a LIDAR to use this SLAM method? I remember during the Summer school, since we tested a lot outdoors, the tracking camera gave problems and we disabled it. 

My use case for my thesis is to perform indoors, is it possible that I can modify and add an implementation to fuse stereo inertial cameras?

Looking forward to your reply,
Aishwarya

**Comment by nubertj** [comment]
Hi @Aishkrish18,
Sorry for the super late reply. In general, it should be possible to add a front-end for feature detection and tracking and use graph_msf as a flexible backend. 
The only worry I would have is that it might be computationally heavy, as our graph formulation includes a lot of (nav-)states at the moment, so it depends a bit what your intended use-case is. Still, the many states might also make your formulation with the camera easy, so running it offline or on a pc might be fairly straightforward.

I once had a similar idea to include visual features, and I think I know how we could make it much more computationally efficient. If you are interested in this, you can also contact me via e-mail: nubertj@ethz.ch

In any case: if you want to use the graph, I would recommend you to use the latest version, as it has many changes. It will be available in a few weeks here, or you can just contact me to get access now.

**Comment by Aishkrish18** [comment]
Sure, I would be highly interested to know more on how we could fuse visual features to perform tracking and localisation, I shall contact you asap with more details via email. 
Thanks :)
Aishwarya

**Comment by Alex-Beh** [comment]
Hi all, I am interested on this topic as well. May I know is it on-going in the background?
